# Format: {A}_{S}
# A = algorithm name, lowercase, without space (must match the src/*.c and src/*.h name)
# S = waiting strategy. original = hardcoded in the algorithm (see README), otherwise spinlock/spin_then_park/park

ALGORITHMS=mcs_spinlock \
concurrency_original \
malthusian_spinlock \
cbomcs_spinlock \
aqmwonode_spin_then_park
